<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32351" started-at="2017-10-12T10:26:32Z" finished-at="2017-10-12T10:27:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32351" started-at="2017-10-12T10:26:32Z" finished-at="2017-10-12T10:27:05Z">
      <class name="com.pack.home.TestExecution.TestRun">
        <test-method status="FAIL" signature="executing()[pri:0, instance:com.pack.home.TestExecution.TestRun@6eebc39e]" name="executing" is-config="true" duration-ms="0" started-at="2017-10-12T15:56:32Z" finished-at="2017-10-12T15:56:32Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.pack.home.Libraries.DriverLaunch.openBrowser(DriverLaunch.java:53)
	at com.pack.home.TestExecution.TestRun.executing(TestRun.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executing -->
        <test-method status="SKIP" signature="passwdlink()[pri:0, instance:com.pack.home.TestExecution.TestRun@6eebc39e]" name="passwdlink" duration-ms="3" started-at="2017-10-12T15:57:05Z" description="Navigate to forgot Password page" finished-at="2017-10-12T15:57:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passwdlink -->
        <test-method status="SKIP" signature="emaillink()[pri:0, instance:com.pack.home.TestExecution.TestRun@6eebc39e]" name="emaillink" duration-ms="2" started-at="2017-10-12T15:57:05Z" description="Enter mail address page " finished-at="2017-10-12T15:57:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emaillink -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:com.pack.home.TestExecution.TestRun@6eebc39e]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-10-12T15:57:05Z" finished-at="2017-10-12T15:57:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.pack.home.TestExecution.TestRun -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
